name: GitHub Actions Demo
on: [push]
jobs:
  firebaseGetGoogleServices:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository 🗿
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      # - name: Install firebase tools 🔥🔨
      #   run: yarn global add firebase-tools
      - run: export $(cat .env >> $GITHUB_ENV | xargs)
      # - name: get_env
      #   run: source ~/.bashrc
      - run: echo ${{ env.FIREBASE_PROJECT }} && echo ${{ env.FIREBASE_TOKEN }} && echo ${{ env.firebaseProjectName }}