name: GitHub Actions Demo
on: [push]
jobs:
  firebaseGetGoogleServices:
    runs-on: ubuntu-latest
    env:
      FIREBASETOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - name: Check out repository 🗿
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      # - name: Install firebase tools 🔥🔨
      #   run: yarn global add firebase-tools
      - name: read from env file
        run : echo $FIREBASETOKEN
      - run : cat .secrets