name: GitHub Actions Demo
on: [push]
jobs:
  firebaseGetGoogleServices:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository 🗿
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      # - name: Install firebase tools 🔥🔨
      #   run: yarn global add firebase-tools
      - run: sudo export $(cat .env >> ~/.bashrc | xargs)
      - run: echo $FIREBASE_PROJECT
      - run: echo $FIREBASE_TOKEN