name: GitHub Actions Demo
on: [push]
jobs:
  firebaseGetGoogleServices:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository 🗿
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      # - name: Install firebase tools 🔥🔨
      #   run: yarn global add firebase-tools
      - name: export env varibles from local
        run: echo export $(cat .env | xargs)
      - run: echo $FIREBASE_PROJECT && echo $FIREBASE_TOKEN