name: GitHub Actions Demo
on: [push]
jobs:
  firebaseGetGoogleServices:
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT: ${{ github.event.inputs.firebaseProject }}
    steps:
      - name: Check out repository 🗿
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      # - name: Install firebase tools 🔥🔨
      #   run: yarn global add firebase-tools
      - name: read from env file
        run : |
          echo ${{ secrets.FIREBASE_TOKEN }}
      - run : cd android && echo "test from gitactions" >> saif.txt && cat saif.txt